class Tenki < Formula
  desc "Animated terminal weather visualisation in pastel ASCII art"
  homepage "https://github.com/phgi/tenki"
  version "0.1.6"
  license "MIT"

  # Prebuilt binaries: installing needs no Rust toolchain and no
  # compilation. This file is generated by .github/workflows/release.yml.
  on_macos do
    on_arm do
      url "https://github.com/phgi/tenki/releases/download/v0.1.6/tenki-0.1.6-aarch64-apple-darwin.tar.gz"
      sha256 "6cd3da63349a64294bb998fdba6571c8b1316a367dd6c417eaa99eded87173ee"
    end
    on_intel do
      url "https://github.com/phgi/tenki/releases/download/v0.1.6/tenki-0.1.6-x86_64-apple-darwin.tar.gz"
      sha256 "f592a5d2d0f843a05813738e5e85cbbc10f08dc51d94f2a654d47d0fcde0c892"
    end
  end

  # `brew install --HEAD` still builds current main from source.
  head do
    url "https://github.com/phgi/tenki.git", branch: "main"
    depends_on "rust" => :build
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "tenki"
    end
  end

  test do
    assert_match "tenki", shell_output("#{bin}/tenki --version")
    assert_match "Open-Meteo", shell_output("#{bin}/tenki --help")
  end
end
