class Tenki < Formula
  desc "Animated terminal weather visualisation in pastel ASCII art"
  homepage "https://github.com/phgi/tenki"
  version "0.1.7"
  license "MIT"

  # Prebuilt binaries: installing needs no Rust toolchain and no
  # compilation. This file is generated by .github/workflows/release.yml.
  on_macos do
    on_arm do
      url "https://github.com/phgi/tenki/releases/download/v0.1.7/tenki-0.1.7-aarch64-apple-darwin.tar.gz"
      sha256 "92b56c7d3129206d29914cbc90f0322bcdaa998aae07d5ff9bf6aadc17edb7ad"
    end
    on_intel do
      url "https://github.com/phgi/tenki/releases/download/v0.1.7/tenki-0.1.7-x86_64-apple-darwin.tar.gz"
      sha256 "ea27b1434f40a6388f16c283ee247558c69d189d29484c52e37f98c8002e00bd"
    end
  end

  # `brew install --HEAD` still builds current main from source.
  head do
    url "https://github.com/phgi/tenki.git", branch: "main"
    depends_on "rust" => :build
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "tenki"
    end
  end

  test do
    assert_match "tenki", shell_output("#{bin}/tenki --version")
    assert_match "Open-Meteo", shell_output("#{bin}/tenki --help")
  end
end
